### ISSUE TITLE
Verification Tool 2.0: Daily Update No. 6

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#242]
**Current status:**

- Made a solid dent in reviewing all the PRs raised by work and Dependabot
- Fixed all known bugs stopping people from using the tool
- On Friday, Zarino and Graeme paired to present all statements in the page for review as a table, where each is acitonable independently.

**Today's goal:**
- [ ] [Chris] Review, merge and deploy Zarino and Graeme's PR #241 
- [x] [Graeme + Zarino] Ordering statements by last name #243 
  - [ ] [Someone] Review Ordering statements by last name #243  
- [x] [Graeme + Zarino] Ordering statements by district and party #244  
  - [ ] [Someone] Review Ordering statements by district and party #244 
- [ ] [Mark L] Review and merge Dependabot PRs
- [x] [Chris or Mark, depending on who finishes first] Investigate the missing transactions for Italy and Canada

**Next goal:**

- [ ] Action statements without needing to press the 'Add to Wikidata' button #249 

**N.B.**

- Sam is still working on deploying a version of Wikibase we can use to develop and test against
